# Test fonction Qualicharge

In [1]:
"""import os
import sys
new_path = os.getcwd()[:-26] + 'qualicharge-rtet'
sys.path.append(new_path)"""

"import os\nimport sys\nnew_path = os.getcwd()[:-26] + 'qualicharge-rtet'\nsys.path.append(new_path)"

In [9]:
import geopandas as gpd
import pandas as pd

from qualicharge_rtet import filter_stations_parcs

data_path = '../data/'
rtet_path = '../rtet/'

version = 'V1'
pcum = 0
pmax= 0

rtet_edges = gpd.read_file(rtet_path + version + '_rtet_edge.geojson')
rtet_nodes = gpd.read_file(rtet_path + version + '_rtet_node.geojson')

#fichier_stations
# engie, electra, e-totem, izivia, ev-cars, ionity, atlante, stations-e, allego, nwiecharge, bouygues, greenyellow, bump
stations_quali_staging = 'export_afir_staging_2025-05-13.csv'
stations_staging = pd.read_csv(data_path + stations_quali_staging, sep=",")
# tesla, powerdot, evzen
stations_quali_production = 'export_afir_production_2025-05-13.csv'
stations_production = pd.read_csv(data_path + stations_quali_production, sep=",")
stations = pd.concat([stations_staging, stations_production], ignore_index=True)

stations_rtet = filter_stations_parcs(rtet_edges, rtet_nodes, stations, only_mandatory=True, simple=True)

Nb stations (st, pre_st, ext, out, total) :  316 2429 3088 5833

In [3]:
stations

,p_max,p_cum,id_station,operateur,amenageur,longitude,latitude
0,22.0,44.0,FRALLEGO999009,EV Cars,EV Cars,1.471787,49.089937
1,22.0,44.0,FRESEPS42095AC,E-Totem,SEMOB,4.286092,45.384258
2,22.0,44.0,FRALLEGO900702,EV Cars,EV Cars,0.372251,49.754217
3,150.0,644.0,FRATLPZ340FRPORTO2000001,Atlante France,Atlante,0.708607,47.320285
4,22.0,132.0,FRETIP34332A,E-Totem,E-TOTEM INFRADIV 2,3.414995,43.289995
...,...,...,...,...,...,...,...
5828,200.0,632.0,FRPD1PALDESN,Power Dot France,Power Dot France,2.512902,48.694318
5829,60.0,132.0,FRPD1PSYUSLA,Power Dot France,Power Dot France,4.191898,43.628977
5830,250.0,5000.0,FRTSLP16321,Tesla,Tesla,3.985209,47.502319
5831,50.0,122.0,FRPD1PITMILC,Power Dot France,Power Dot France,1.256011,48.304153
5832,22.0,88.0,FREVZPBC4DADF27C9A41CEA91545988A706,EVzen,SMEG DEVELOPPEMENT,4.033611,46.275770

In [10]:
stations_rtet

,id_station_itinerance,core,node_id,parc_nature,parc_geometry,parc_id
0,FRESEPS42095AC,False,3511,rond-point,POINT (800245.6643393867 6477539.172711838),parc 3328
1,FRATLPZ340FRPORTO2000001,True,3513,echangeur,POINT (525792.093440908 6694619.001740126),parc 2539
2,FRALLEGO900541,False,3521,echangeur,POINT (571999.41607194 6280327.782460517),parc 2990
3,FRALLEGO900067,False,3523,echangeur,POINT (567663.5947658009 6880992.000732965),parc 2900
4,FRLMSP89786298,False,3524,echangeur,POINT (458946.8092929806 6901090.2931184145),parc 2911
...,...,...,...,...,...,...
2135,FRTSLP2986,False,9168,aire de service,POINT (846044.4000000001 6774696.599999999),parc 1059
2136,FRTSLP29498,True,9193,aire de service,POINT (847303.8183620396 6420255.779885585),parc 950
2137,FRTSLP5671,True,9246,aire de service,POINT (942260.4067930306 6262889.166853477),parc 998
2138,FRTSLP3319,False,9288,aire de service,POINT (877344.846483561 6602122.607092863),parc 769
2139,FRTSLP1744,False,9321,aire de service,POINT (725089.443595032 6307226.291549408),parc 1260